name: smart_dispense_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  freezed_annotation: ^1.0.0
  pretty_dio_logger: ^1.1.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.0.1

flutter:

