include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    avoid_implementing_value_types: false
    sort_pub_dependencies: false
    
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  errors:
    unused_import: error
    # TODO: Remove invalid_annotation_target after this is solved:
    #   - https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
    prefer_constructors_over_static_methods: ignore